### ISSUE TITLE
Sound mute

### ISSUE THREAD

**Issue by phyne** [OreCruncher/SoundControl#1]
Sounds can be noticed "building up" in the sound control engine. I won't claim to know how it works, but it is easily noticed in the debug screen - "SoundSystem x/255" will fill up to 255, after which no new sounds will play. This seems 100% reproducible after reloading resource packs. A full reboot of Minecraft is necessary to resolve the issue.

I'll try to isolate the mod and/or resource packs and see if anything is conflicting, but I figured I'd drop the issue in ASAP since nobody else submitted anything.

EDIT: The issue indeed persists with nothing but Forge 28.1.111, SoundControl, and the default resource pack. Just load 'er up and give it a quick F3+T.

![2020-01-02_18 39 11](https://user-images.githubusercontent.com/30962920/71699820-71245080-2d8f-11ea-8335-6f0f722d1be6.png)
[debug.txt](https://github.com/OreCruncher/SoundControl/files/4017744/debug.txt)

**Comment by OreCruncher** [comment]
Thanks for the issue and the log.  It confirmed what I was suspecting.  I will have a fix posted this weekend.  Is is related to reloading resource packs and the like.  The sound engine reinitializes, and when that happens the config work I did for OpenAL gets reset and things go sideways.
