### ISSUE TITLE
1.15.2 Crash with EnderStorage

### ISSUE THREAD

**Issue by Klaaf** [OreCruncher/SoundControl#14]
Hello! I'm not sure this is coming from this mod or not.
The game crashes when trying to render ender chest or ender tank tile entities.

Game version: 1.15.2
Forge Version: 31.2.45
Environ Version: 1.0.0
MobEffects: 1.0.0
SoundControl; 1.0.0.1
Enderstorage: 2.5.0.151

Crash log: https://gist.github.com/Klaaf/f31d02a66a60c7274dd18d03424d0267

Btw thank you for your work, I'm happy to see your mods on newer versions!

**Comment by OreCruncher** [comment]
Moved the issue to the right tracker.  I posted a fix to CurseForge (1.15.2-1.0.0.2).  The problem was the entity passed into the attach capability event had a null world, which based on the API contract should not happen.
