### ISSUE TITLE
[1.14.4] Crash when changing Mipmap levels in-game - (Modpack)

### ISSUE THREAD

**Issue by Gbergz** [OreCruncher/SoundControl#2]
Game crashed when it was done changing a mipmap level in-game.

Crash-report: [https://gist.github.com/Gbergz/fae48fc6d4b27a400fa271b11a56ae78](https://gist.github.com/Gbergz/fae48fc6d4b27a400fa271b11a56ae78)

MC-Version: **1.14.4**
Forge Version: **28.1.107**
Mod-Version: **0.0.3.0**

**Comment by OreCruncher** [comment]
Do you happen to have your client side debug.log for this even?

**Comment by Gbergz** [comment]
Nope, no debug log available in **/logs/** only the **latest.log**.

**Comment by OreCruncher** [comment]
Post that - may get lucky. ;)

**Comment by Gbergz** [comment]
Coming up, soon-ish!

**Comment by OreCruncher** [comment]
Thanks!  Also, do you have the enhanced sounds enabled or disabled?  Cave reverb, etc.

**Comment by Gbergz** [comment]
For me i've disabled the Cave Reverbs etc.

**Comment by OreCruncher** [comment]
Ah!  I think I know what the problem is.  BTW, I am curious as to why you have them disabled.  No criticism - I am just curious. :)

**Comment by Gbergz** [comment]
Logs:
[https://gist.github.com/Gbergz/60d3a4c7348d4edfd32c3f2005a344ad](https://gist.github.com/Gbergz/60d3a4c7348d4edfd32c3f2005a344ad)

**Comment by Gbergz** [comment]
I don't know really, i like the reverbs etc but when the sounds get muffled behind blocks that i didn't like. Maybe i just looked at the wrong place and you could disable just that.

**Comment by OreCruncher** [comment]
Sound occlusion.  There isn't an option to independently disable that calculation.  I will add to my list of things to investigate.

**Comment by Gbergz** [comment]
Any idea when this will be pushed?
No hurry ofcourse as its not a HUGE issue.

**Comment by OreCruncher** [comment]
Not entirely sure yet.  I have other changes that are in process that need to be tested on my end.  Am thinking sometime tomorrow.

**Comment by Gbergz** [comment]
Alright, were thinking of releasing a new update of my pack. Guess i'll just wait until tomorrow or release a "a/b" update, when you've released it :)

**Comment by Gbergz** [comment]
Heya again, one of my users just reported a crash when he launched the pack. I didn't get this crash so it seems random? Anyways i'm using all the latest versions available and forge is 28.1.107

Crash-Report: [https://gist.github.com/Gbergz/541b5d95a4119b8e862acfdebe645f38](https://gist.github.com/Gbergz/541b5d95a4119b8e862acfdebe645f38)

**Comment by OreCruncher** [comment]
This one I think I need to see the client log.  The error is quite strange.

**Comment by Gbergz** [comment]
Will send you it if I or him experience it again.

**Comment by OreCruncher** [comment]
Pushed 0.0.4.0 to CurseForge with a fix for the crash as well as an option to disable block occlusion.
