### ISSUE TITLE
Config Option to disable F3 Debug Info

### ISSUE THREAD

**Issue by WenXin20** [OreCruncher/SoundControl#7]
`Minecraft v1.14.4`
`Sound Control v0.0.5.0`

Can a config option to disable the extra F3 debug info be added? 
With all the information being added, I'm unable to view the F3 debug information other mods add to the screen, without having to disable this mod.

**Comment by OreCruncher** [comment]
It's on my list.  DS originally only displayed the info if debug tracing was enabled, and I want to do the same thing with these mods.

**Comment by OreCruncher** [comment]
Pushed release build 0.1.0.0 to CurseForge
